//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.24 at 12:49:00 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://agora.nibodha.com/schema/transformation", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.nibodha.agora.services.objectmapper.config;
